### ISSUE TITLE
Upgrade to Typescript.

### ISSUE THREAD

**Issue by RHarrison-** [coventryuniversity/mozbugs#2]
I'd like to start writing my additions and improvements using Typescript. This will make the code base much easier to understand, and faster for new contributors to get up to speed. 

I'd be happy to upgrade all the existing code to typescript too.  

I don't currently have permissions to create a branch on this repository for my current changes.  I have a PR ready for review with a update the bug store once I can push my branch 👍🏻

@benjaminbogdanovic

**Comment by benjaminbogdanovic** [comment]
To make life simpler for both of us I have added you as collaborator on the repository.

Don’t break anything ;)
