### ISSUE TITLE
Selecting filters while bugs are being retrieved causes additional unnecessary Bugzilla requests.

### ISSUE THREAD

**Issue by RHarrison-** [coventryuniversity/mozbugs#4]
Selecting a filter before the bugs have loaded causes another request to be created. By clicking as fast as possible you can spawn dozens of HTTP requests to the Bugzilla severs to request the same set of bugs over and over again.

![oops](https://i.gyazo.com/f35aa792936812004dc8be0d2706f29e.gif)

**Comment by benjaminbogdanovic** [comment]
Is this a new bug due to the changes you made?

**Comment by RHarrison-** [comment]
It appears so, found the culprit. PR #5, fixes this issue, one single word change!
